config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :comments, only: [:index, :new, :create], module: :events
  end

  resources :articles do
    resources :comments, only: [:index, :new, :create], module: :articles
  end

  resources :posts do
    resources :comments, only: [:index, :new, :create], module: :posts
  end

  resources :tags, only: [:show]

  resources :comments, only: [:show, :edit, :update, :destroy]

  root 'welcome#index'

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  title      :text
#  address    :text
#  started_at :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  tag_slugs  :text             default([]), is an Array
#

class Event < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 4 }
  validates :address, presence: true
  validates :started_at, presence: true

  paginates_per 6

  has_many :comments, as: :target
end

app/controllers/events/comments_controller.rb
class Events::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Event.find(params[:event_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.order('updated_at DESC').page params[:page]
  end

  def show
    @event = Event.find(params[:id])
    if stale?(@event)
      @comments = @event.comments.order('updated_at DESC').page params[:page]
      @tags = @event.tag_slugs
    end
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to events_path
  end

  private

  def event_params
    params.require(:event).permit(:title, :address, :started_at)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.slim
h1
  = t 'events._event.title'
  = link_to event.title, article_path(event)
p
  = t 'events._event.at_location'
  = event.address
  = t 'events._event.on_date'
  = event.started_at
br
div 
  = t 'events._event.tags'
  - event.tag_slugs.each do |tag|
    span.label.label-default = link_to tag, controller: 'tags', action: 'show', id: tag
br

app/views/events/edit.html.slim
= form_for @event, method: :patch, html: { class: 'form-horizontal' } do |f|
  
  - if @event.errors.any?
    #error_explanation
      h2
        = pluralize(@event.errors.count, "error")
        |  prohibited this event from being saved:
      ul
        - @event.errors.full_messages.each do |msg|
          li = msg

  fieldset
    legend Editing Event
    .form-group
      = f.label :title, class: 'col-lg-2 control-label'
      .col-lg-10
        = f.text_field :title, class: 'form-control'
    .form-group
      = f.label :address, class: 'col-lg-2 control-label'
      .col-lg-10
        = f.text_field :address, class: 'form-control'
    .form-group
      = f.label :started_at, class: 'col-lg-2 control-label'
      .col-lg-10
        = f.date_select :started_at, class: 'form-control'
    .form-group
      = f.label :tag_slugs, class: 'col-lg-2 control-label'
      .col-lg-10
        = f.select(:tag_slugs, Tag.all.collect {|tag| [tag.slug, tag.slug] }, {}, {class: 'form-control list-tags', multiple: true})
    .form-group
      .col-lg-10.col-lg-offset-2
        = link_to 'Back', events_path, class: 'btn btn-default'
        = f.submit 'Submit', class: 'btn btn-primary'

app/views/events/index.html.slim
h1 = t 'events.index.title'

= link_to 'New Event', new_event_path

- @events.each do |event|
  h3 = link_to event.title, event_path(event)
  p 
    = event.address
    = t 'events.index.on_date'
    = event.started_at
  = link_to 'Edit', edit_event_path(event)
br
= paginate @events

app/views/events/new.html.slim
= form_for @event, html: { class: 'form-horizontal' } do |f|
  
  - if @event.errors.any?
    #error_explanation
      h2
        = pluralize(@event.errors.count, "error")
        = t 'errors.error_message'
      ul
        - @event.errors.full_messages.each do |msg|
          li = msg

  fieldset
    legend = t 'events.new.legend'
    .form-group
      = f.label :title, class: 'col-lg-2 control-label'
      .col-lg-10
        = f.text_field :title, class: 'form-control'
    .form-group
      = f.label :address, class: 'col-lg-2 control-label'
      .col-lg-10
        = f.text_field :address, class: 'form-control'
    .form-group
      = f.label :started_at, class: 'col-lg-2 control-label'
      .col-lg-10
        = f.date_select :started_at, class: 'form-control'
    .form-group
      = f.label :tag_slugs, class: 'col-lg-2 control-label'
      .col-lg-10
        = f.select(:tag_slugs, Tag.all.collect {|tag| [tag.slug, tag.slug] }, {}, {class: 'form-control list-tags', multiple: true})
    .form-group
      .col-lg-10.col-lg-offset-2
        = link_to 'Back', events_path, class: 'btn btn-default'
        = f.submit 'Submit', class: 'btn btn-primary'

app/views/events/show.html.slim
h1 = @event.title
p = @event.address
= t 'events.show.on_date'
= @event.started_at
br
div 
  = t 'events.show.tags'
  - @tags.each do |tag|
    span.label.label-default = link_to tag, controller: 'tags', action: 'show', id: tag
br
br
= link_to 'Back', events_path

= render template: 'comments/index', locals: { commentable: @comments }

= render template: 'comments/new', locals: { commentable: @event } 