config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :comments, only: [:index, :new, :create], module: :events
  end

  resources :articles do
    resources :comments, only: [:index, :new, :create], module: :articles
  end

  resources :posts do
    resources :comments, only: [:index, :new, :create], module: :posts
  end

  resources :tags, only: [:show]

  resources :comments, only: [:show, :edit, :update, :destroy]

  root 'welcome#index'

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :text
#  slug       :text
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  tag_slugs  :text             default([]), is an Array
#  settings   :hstore           default({}), not null
#

class Post < ActiveRecord::Base
  include Taggable
  include CustomFields

  validates :title, presence: true, length: { minimum: 4 }
  validates :content, presence: true

  custom_fields :title_bg_color, :font_size

  paginates_per 5

  has_many :comments, as: :target
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order('updated_at DESC').page params[:page]
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.order('updated_at DESC').page params[:page]
    @tags = @post.tag_slugs
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :slug, :title_bg_color,
                                 :font_size, tag_slugs: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.slim
h1
  = t '_post.name'
  = link_to post.title, article_path(post)
p
  = t '_post.with_slug' 
  = post.slug
br
div 
  = t '_post.tags'
  - post.tag_slugs.each do |tag|
    span.label.label-default = link_to tag, controller: 'tags', action: 'show', id: tag
br

app/views/posts/edit.html.slim
= form_for @post, method: :patch, html: { class: 'form-horizontal' } do |f|

  - if @post.errors.any?
      #error_explanation
        h2
          = pluralize(@post.errors.count, 'error') 
          = t 'errors.error_message'
        ul
          - @post.errors.full_messages.each do |msg|
            li = msg
  fieldset
    legend = t 'posts.edit.legend'

    .form-group
      = f.label :title, class: 'col-lg-2 control-label'
      .col-lg-10
        = f.text_field :title, class: 'form-control'
    .form-group
      = f.label :title_bg_color, class: 'col-lg-2 control-label'
      .col-lg-10
        = f.select(:title_bg_color, ['info', 'success', 'warning', 'normal'], {}, {class: 'form-control', id: 'list-title_bg_color'})
    .form-group
      = f.label :font_size, class: 'col-lg-2 control-label'
      .col-lg-10
        = f.select(:font_size, ['small', 'medium', 'big'], {}, {class: 'form-control', id: 'list-font_size'})
    .form-group
      = f.label :content, class: 'col-lg-2 control-label'
      .col-lg-10
        = f.text_area :content, class: 'form-control', rows: 10
    .form-group
      = f.label :tag_slugs, class: 'col-lg-2 control-label'
      .col-lg-10
        = f.select(:tag_slugs, Tag.all.collect {|tag| [tag.slug, tag.slug] }, {}, {class: 'form-control list-tags', multiple: true})
    .form-group
      .col-lg-10.col-lg-offset-2
        = link_to 'Back', posts_path, class: 'btn btn-default'
        = f.submit 'Submit', class: 'btn btn-primary'

app/views/posts/index.html.slim
h1 = t 'index.header'

= link_to 'New Post', new_post_path
- @posts.each do |post|
  - cache(post) do
    h3 
      = link_to post.title, post_path(post)
    .elipsis_4_lines = post.content
    = link_to 'Edit', edit_post_path(post)
    |  
    = link_to 'Destroy', post_path(post),
                method: :delete,
                data: { confirm: 'Are you sure?' }
br
= paginate @posts

app/views/posts/new.html.slim
= form_for @post, html: { class: 'form-horizontal' } do |f|
  
  - if @post.errors.any?
    #error_explanation
      h2
        = pluralize(@post.errors.count, "error")
        = t 'errors.error_message'
      ul
        - @post.errors.full_messages.each do |msg|
          li = msg

  fieldset
    legend = t 'posts.edit.legend'
    .form-group
      = f.label :title, class: 'col-lg-2 control-label'
      .col-lg-10
        = f.text_field :title, class: 'form-control'
    .form-group
      = f.label :title_bg_color, class: 'col-lg-2 control-label'
      .col-lg-10
        = f.select(:title_bg_color, ['info', 'success', 'warning', 'normal'], {}, {class: 'form-control', id: 'list-title_bg_color'})
    .form-group
      = f.label :font_size, class: 'col-lg-2 control-label'
      .col-lg-10
        = f.select(:font_size, ['small', 'medium', 'big'], {}, {class: 'form-control', id: 'list-font_size'})
    .form-group
      = f.label :content, class: 'col-lg-2 control-label'
      .col-lg-10
        = f.text_area :content, class: 'form-control', rows: 10
    .form-group
      = f.label :tag_slugs, class: 'col-lg-2 control-label'
      .col-lg-10
        = f.select(:tag_slugs, Tag.all.collect(&:slug), {}, {class: 'form-control', id: 'list-tags', multiple: true})
    .form-group
      .col-lg-10.col-lg-offset-2
        = link_to 'Back', posts_path, class: 'btn btn-default'
        = f.submit 'Submit', class: 'btn btn-primary'

app/views/posts/show.html.slim
h1 class="#{@post.title_bg_color}"
  = @post.title
div class="#{@post.font_size}-content"
  = simple_format(@post.content)
br
div 
  = t 'posts.show.tags' 
  - @tags.each do |tag|
    span.label.label-default = link_to tag, controller: 'tags', action: 'show', id: tag
br
br
= link_to 'Back', posts_path

= render template: 'comments/index', locals: { commentable: @comments }

= render template: 'comments/new', locals: { commentable: @post }